/**
 * formatters/html.js — HTML export formatter
 * Produces both Netscape bookmark format (browser-importable) and rich gallery HTML.
 * Single Responsibility: convert raw API data to HTML strings
 */

import {
  escapeHtml,
  formatDate,
  toUnixTimestamp,
  groupByCollection,
  HIGHLIGHT_COLORS,
} from '../utils.js';

// ---------------------------------------------------------------------------
// Netscape Bookmark Format (importable into Chrome/Firefox/Safari)
// ---------------------------------------------------------------------------

/**
 * Format as Netscape Bookmark HTML.
 * @param {object} payload
 * @param {Map} collectionMap
 * @returns {string}
 */
export function formatNetscapeHTML(payload, collectionMap) {
  const groups = groupByCollection(payload.raindrops, collectionMap);
  let html = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
`;

  for (const [collTitle, items] of groups) {
    html += `    <DT><H3 ADD_DATE="0">${escapeHtml(collTitle)}</H3>\n    <DL><p>\n`;
    for (const rd of items) {
      const addDate = toUnixTimestamp(rd.created);
      const lastMod = toUnixTimestamp(rd.lastUpdate);
      const tags = (rd.tags || []).join(', ');
      const iconAttr = rd.cover ? ` ICON="${escapeHtml(rd.cover)}"` : '';
      html += `        <DT><A HREF="${escapeHtml(rd.link)}" ADD_DATE="${addDate}" LAST_MODIFIED="${lastMod}"${iconAttr}${tags ? ` TAGS="${escapeHtml(tags)}"` : ''}>${escapeHtml(rd.title || rd.link)}</A>\n`;
      if (rd.excerpt) {
        html += `        <DD>${escapeHtml(rd.excerpt)}\n`;
      }
    }
    html += `    </DL><p>\n`;
  }

  html += `</DL><p>\n`;
  return html;
}

// ---------------------------------------------------------------------------
// Rich HTML (visual gallery with thumbnails, tags, highlights, notes)
// ---------------------------------------------------------------------------

/**
 * Format as rich HTML gallery.
 * @param {object} payload
 * @param {Map} collectionMap
 * @returns {string}
 */
export function formatRichHTML(payload, collectionMap) {
  const groups = groupByCollection(payload.raindrops, collectionMap);
  const exportDate = formatDate(payload.exportedAt);

  const cards = [];
  for (const [collTitle, items] of groups) {
    cards.push(`
      <section class="collection" id="col-${escapeHtml(collTitle.replace(/\s+/g, '-'))}">
        <h2 class="collection-title">${escapeHtml(collTitle)} <span class="count">${items.length}</span></h2>
        <div class="cards">
          ${items.map(renderCard).join('\n')}
        </div>
      </section>`);
  }

  // Build collection nav
  const navLinks = [...groups.keys()]
    .map((t) => `<a href="#col-${escapeHtml(t.replace(/\s+/g, '-'))}">${escapeHtml(t)}</a>`)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Raindrop.io Export — ${exportDate}</title>
  <style>${getCSS()}</style>
</head>
<body>
  <header>
    <h1>🔖 Raindrop.io Export</h1>
    <p class="meta">
      Exported: <strong>${escapeHtml(exportDate)}</strong> &nbsp;|&nbsp;
      ${payload.raindrops.length} bookmarks &nbsp;|&nbsp;
      ${payload.collections.length} collections
    </p>
  </header>
  <nav class="collection-nav">
    <strong>Collections:</strong>
    ${navLinks}
  </nav>
  <main>
    ${cards.join('\n')}
  </main>
  <footer><p>Generated by Raindrop.io Exporter v1.0.0</p></footer>
</body>
</html>`;
}

function renderCard(rd) {
  const coverImg = rd.cover
    ? `<div class="cover"><img src="${escapeHtml(rd.cover)}" alt="" loading="lazy" onerror="this.parentElement.style.display='none'"></div>`
    : '';

  const tagPills = (rd.tags || []).length
    ? `<div class="tags">${rd.tags.map((t) => `<span class="tag">${escapeHtml(t)}</span>`).join('')}</div>`
    : '';

  const meta = [
    rd.domain ? `<span class="domain">${escapeHtml(rd.domain)}</span>` : '',
    rd.created ? `<span class="date">${escapeHtml(formatDate(rd.created))}</span>` : '',
    rd.type !== 'link' ? `<span class="type type-${escapeHtml(rd.type)}">${escapeHtml(rd.type)}</span>` : '',
    rd.important ? `<span class="favorite">⭐</span>` : '',
    rd.broken ? `<span class="broken" title="Link may be broken">⚠️</span>` : '',
  ].filter(Boolean).join(' &middot; ');

  const excerpt = rd.excerpt
    ? `<p class="excerpt">${escapeHtml(rd.excerpt.slice(0, 300))}${rd.excerpt.length > 300 ? '…' : ''}</p>`
    : '';

  const note = rd.note
    ? `<blockquote class="note">${escapeHtml(rd.note)}</blockquote>`
    : '';

  const highlights = (rd.highlights || []).length
    ? `<div class="highlights">${rd.highlights.map((h) => {
        const bg = HIGHLIGHT_COLORS[h.color] || HIGHLIGHT_COLORS.yellow;
        return `<span class="highlight" style="background:${bg}">${escapeHtml(h.text)}</span>`;
      }).join('')}</div>`
    : '';

  return `<article class="card${rd.important ? ' favorite' : ''}${rd.broken ? ' broken' : ''}">
  ${coverImg}
  <div class="body">
    <a class="title" href="${escapeHtml(rd.link)}" target="_blank" rel="noopener">${escapeHtml(rd.title || rd.link)}</a>
    <div class="meta">${meta}</div>
    ${tagPills}
    ${excerpt}
    ${note}
    ${highlights}
  </div>
</article>`;
}

function getCSS() {
  return `
:root {
  --bg: #f8fafc; --card-bg: #fff; --accent: #6366f1;
  --text: #1e293b; --muted: #64748b; --border: #e2e8f0;
  --tag-bg: #ede9fe; --tag-text: #5b21b6;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui,-apple-system,sans-serif; background: var(--bg); color: var(--text); line-height: 1.5; }
header { padding: 2rem; background: var(--accent); color: #fff; }
header h1 { font-size: 1.8rem; }
header .meta { margin-top: 0.5rem; opacity: 0.9; }
nav.collection-nav { padding: 1rem 2rem; background: #fff; border-bottom: 1px solid var(--border); display: flex; flex-wrap: wrap; gap: 0.5rem; font-size: 0.85rem; }
nav a { color: var(--accent); text-decoration: none; padding: 2px 8px; border-radius: 99px; border: 1px solid var(--accent); }
nav a:hover { background: var(--accent); color: #fff; }
main { max-width: 1200px; margin: 0 auto; padding: 2rem; }
.collection { margin-bottom: 3rem; }
.collection-title { font-size: 1.3rem; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid var(--border); display: flex; justify-content: space-between; }
.count { font-size: 0.9rem; color: var(--muted); font-weight: normal; }
.cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 1rem; }
.card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 10px; overflow: hidden; display: flex; flex-direction: column; transition: box-shadow .15s; }
.card:hover { box-shadow: 0 4px 20px rgba(0,0,0,.08); }
.card.favorite { border-color: #fbbf24; }
.card.broken { opacity: 0.65; }
.cover img { width: 100%; height: 140px; object-fit: cover; display: block; }
.body { padding: 0.9rem; flex: 1; display: flex; flex-direction: column; gap: 0.4rem; }
.title { font-weight: 600; color: var(--accent); text-decoration: none; font-size: 0.95rem; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.title:hover { text-decoration: underline; }
.meta { font-size: 0.75rem; color: var(--muted); }
.domain { font-weight: 500; }
.type { background: #e0f2fe; color: #0369a1; padding: 1px 6px; border-radius: 99px; font-size: 0.7rem; text-transform: uppercase; }
.tags { display: flex; flex-wrap: wrap; gap: 4px; }
.tag { background: var(--tag-bg); color: var(--tag-text); padding: 2px 8px; border-radius: 99px; font-size: 0.7rem; }
.excerpt { font-size: 0.82rem; color: var(--muted); }
.note { border-left: 3px solid var(--accent); padding-left: 0.75rem; font-size: 0.82rem; color: var(--muted); font-style: italic; }
.highlights { display: flex; flex-direction: column; gap: 4px; }
.highlight { padding: 3px 6px; border-radius: 4px; font-size: 0.8rem; }
footer { text-align: center; padding: 2rem; color: var(--muted); font-size: 0.8rem; }
`;
}
