/**
 * formatters/markdown.js — Markdown export formatter
 * Single Responsibility: convert raw API data to Markdown string
 */

import {
  escapeMarkdown,
  escapeMarkdownTable,
  formatDate,
  groupByCollection,
} from '../utils.js';

/**
 * Format as Markdown document.
 * @param {object} payload
 * @param {Map} collectionMap
 * @returns {string}
 */
export function formatMarkdown(payload, collectionMap) {
  const groups = groupByCollection(payload.raindrops, collectionMap);
  const exportDate = formatDate(payload.exportedAt);

  const lines = [
    `# 🔖 Raindrop.io Export`,
    ``,
    `> **Exported:** ${exportDate}  `,
    `> **Total bookmarks:** ${payload.raindrops.length}  `,
    `> **Collections:** ${payload.collections.length}`,
    ``,
    `---`,
    ``,
    `## Table of Contents`,
    ``,
  ];

  // TOC
  for (const collTitle of groups.keys()) {
    const anchor = collTitle.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
    lines.push(`- [${escapeMarkdown(collTitle)}](#${anchor})`);
  }
  lines.push('', '---', '');

  // Per-collection sections
  for (const [collTitle, items] of groups) {
    lines.push(`## ${escapeMarkdown(collTitle)}`);
    lines.push('');
    lines.push(`*${items.length} bookmark${items.length !== 1 ? 's' : ''}*`);
    lines.push('');

    for (const rd of items) {
      const title = rd.title || rd.link || 'Untitled';
      lines.push(`### [${escapeMarkdown(title)}](${rd.link || ''})`);
      lines.push('');

      // Metadata table
      const metaRows = [];
      if (rd.domain)       metaRows.push(`| Domain | \`${escapeMarkdownTable(rd.domain)}\` |`);
      if (rd.type)         metaRows.push(`| Type | ${escapeMarkdownTable(rd.type)} |`);
      if (rd.created)      metaRows.push(`| Added | ${escapeMarkdownTable(formatDate(rd.created))} |`);
      if (rd.lastUpdate)   metaRows.push(`| Updated | ${escapeMarkdownTable(formatDate(rd.lastUpdate))} |`);
      if (rd.important)    metaRows.push(`| Favourite | ⭐ Yes |`);
      if (rd.broken)       metaRows.push(`| Status | ⚠️ Link may be broken |`);
      if (rd.cover)        metaRows.push(`| Cover | [Preview](${escapeMarkdownTable(rd.cover)}) |`);

      if (metaRows.length) {
        lines.push('| Field | Value |');
        lines.push('|-------|-------|');
        lines.push(...metaRows);
        lines.push('');
      }

      // Tags
      if ((rd.tags || []).length) {
        lines.push(`**Tags:** ${rd.tags.map((t) => `\`${escapeMarkdown(t)}\``).join(', ')}`);
        lines.push('');
      }

      // Excerpt
      if (rd.excerpt) {
        lines.push(`> ${rd.excerpt.replace(/\n/g, '\n> ')}`);
        lines.push('');
      }

      // Note
      if (rd.note) {
        lines.push(`**Note:** ${escapeMarkdown(rd.note)}`);
        lines.push('');
      }

      // Highlights
      if ((rd.highlights || []).length) {
        lines.push('**Highlights:**');
        lines.push('');
        for (const h of rd.highlights) {
          const colorLabel = h.color ? ` *(${h.color})*` : '';
          lines.push(`- ${escapeMarkdown(h.text)}${colorLabel}`);
          if (h.note) lines.push(`  - Note: ${escapeMarkdown(h.note)}`);
        }
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    }
  }

  lines.push(`*Generated by Raindrop.io Exporter v1.0.0*`);
  return lines.join('\n');
}
